# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e924890d123b544a4c888717ca4297b264a2ead5d50ff7abe27dba7d0deac2594cb1c7457970862e6db7936135b17f465d46a7e40db574ca3031036a79206e98

test:
  secret_key_base: da8374838482c9d14facfb40505dd4f53ef5a5ac5aa3cf91ed1c3f0fe4e0b3ee393ff7c807f997b954c768f6671af032426a5e855880dd19584a37c30cdba9c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
